debug: false
management.endpoints.web.exposure.include: "*"

spring:
  thymeleaf3:
    decoupled-logic: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/my-db-test;mode=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  cache:
        type: redis
  redis:
      host: localhost
      port: 6379
  servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 20MB
            location: /Users/brinc/Desktop/brincestudy/JAVA/df-toy-project/src/main/resources/static/images/imgSaveFolder/
            enabled: true
  jpa:
    defer-datasource-initialization: true
    open-in-view: true

    hibernate.ddl-auto: create
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100

  sql:
    init:
      mode: always
  devtools:
    remote:
      restart:
        enabled: true

com:
  example:
    upload:
      path:
        profileImg: "/Users/brinc/Desktop/brincestudy/JAVA/df-toy-project/src/main/resources/static/images/imgSaveFolder/"